name: Build Flet APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install Flet
        run: pip install "flet[all]"
        
      - name: Build APK
        # Añadimos --no-interactive para que no pida confirmaciones por consola
        run: flet build apk --no-interactive
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/apk/*.apk
